### ISSUE TITLE
`i2c_write_byte` discards byte if TX FIFO buffer is full

### ISSUE THREAD

**Issue by constant-flow** [vmilea/pico_i2c_slave#1]
Hi thx for the library code u provided. This got me a working back and forth comm with an ESP32 with wire library.

I had to add some stall loops to the `i2c_write_byte` function to transmit multiple bytes (20) in a row. Without the code only 17 went thru.

I added the `i2c_wait_until_ready_to_write` function, which I then use in `i2c_write_byte` to make sure the buffer is ready to send.

```
/**
 * \brief Checks the Tx FIFO if not full
 * If full stall for maximum `max_wait_loops` times, 
 * returns false if the buffer was still full.
 * 
 * \param i2c I2C instance.
 * \param max_wait_loops stall this amount of loops until buffer is ready.
 */
    static inline bool i2c_wait_until_ready_to_write(i2c_inst_t *i2c, uint16_t max_wait_loops)
    {
        i2c_hw_t *hw = i2c_get_hw(i2c);
        while (!(hw->status & I2C_IC_STATUS_TFNF_BITS))
        {
            if (max_wait_loops-- == 0)
                return false;
        }
        return true;
    }

/**
 * \brief Push a byte into I2C Tx FIFO.
 * 
 * \param i2c I2C instance.
 * \param value Byte value.
 */
    static inline void i2c_write_byte(i2c_inst_t *i2c, uint8_t value)
    {
        i2c_hw_t *hw = i2c_get_hw(i2c);
        i2c_wait_until_ready_to_write(i2c, 3000);                     // required to wait for tx buffer to send
        hard_assert_if(I2C, !(hw->status & I2C_IC_STATUS_TFNF_BITS)); // Tx FIFO must not be full
        hw->data_cmd = value;
    }
```

maybe there is a better way to request a flush/send.

**Comment by vmilea** [comment]
Hi. I'm glad you found the code useful.

`i2c_write_byte()` is supposed to panic if the Tx FIFO is full. Unfortunately, in the the latest SDK `PARAM_ASSERTIONS_ENABLED_I2C` defaults to `0` so the assert is disabled.

**Comment by vmilea** [comment]
Here is some context for clarity:

The I2C controller on the RP2040 has a 16 byte Tx FIFO. If it's full, any additional data written to `IC_DATA_CMD.DAT` gets discarded. This explains why only 17 bytes were going through (first byte starts transmitting immediately, the next 16 go into the FIFO, and the rest get discarded).

When transmitting data as a slave, it's best to split it into chunks. So you write as much as will fit into the Tx FIFO (`i2c_get_write_available()`), then on the next  `handler` call write the next chunk and so on. This avoids stalling the I2C IRQ handler, and lets the slave react quickly should the master abort the transfer. The `i2c_write_byte()` function was designed for this pattern, hence the hard assert that Tx FIFO must not be full.

But often your approach can work just fine. In fact, this is precisely how the [Wire wrapper](https://github.com/vmilea/pico_i2c_slave/blob/1c4b3bd17a3d7a64b672dc08922bc0b998c26042/example_mem_wire/Wire.cpp#L118) avoids overflow. So that one may be easier to use than the basic API.

**Comment by constant-flow** [comment]
Thank you for your precise elaboration. I'll check out if the Wire wrapper works for me as well, but it should.

I guess this issue can be closed. Maybe a little hint near the `i2c_write_byte` or the Readme about the 16 byte buffer could  help others. Even better would be a more complex example sending multiple bytes (did I hear a `hello world`?) on request.

thx for your quick support 😃

**Comment by vmilea** [comment]
I've updated the documentation, hopefully it's a bit more clear now. Planning to add a more complex example when I find time.

**Comment by constant-flow** [comment]
Switching to Wire worked flawlessly. I now use your lib next to the pico-sdk in my project as a dependency.
